In [8]:
%load_ext autoreload
%autoreload 2

In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('.'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [9]:
import importlib
from protonets.models import few_shot_statistic_pooling
import torch
import torch.nn as nn

In [3]:
kwargs = {}
kwargs['layer_sizes'] = [512, 512, 512, 512, 3 * 512]
kwargs['kernel_sizes'] = [5, 5, 7, 1, 1]
kwargs['embedding_sizes'] = [512, 200]
kwargs['feature_dim'] = 60
kwargs['dropout_keep_prob'] = 0.9

In [48]:
model = few_shot_statistic_pooling.load_few_short_speech(**kwargs)

In [39]:
n_class = 10
n_query = 5
n_support = 5
max_len = 400
mfcc_dim = 60
batch = {}
batch['xq_padded'] = torch.rand(n_class, n_query, max_len, mfcc_dim) # n_class * n_query * max_len * mfcc_dim
batch['xs_padded'] = torch.rand(n_class, n_support, max_len, mfcc_dim) # n_class * n_support * max_len * mfcc_dim
batch['xq_len'] = (torch.rand(n_class, n_query) * 200).int() # n_class * n_query 
batch['xs_len'] = (torch.rand(n_class, n_support) * 200).int() # n_class * n_support

In [40]:
batch['xq_len']

tensor([[  36,   17,  196,   15,  125],
        [  68,   30,   96,  147,  169],
        [  38,   60,   79,   69,  157],
        [  11,  156,  130,  184,   68],
        [ 146,  176,  131,   97,   51],
        [  38,   96,  114,   47,   88],
        [ 132,   37,  124,   57,   33],
        [  11,   11,   56,   59,  128],
        [  62,  165,  195,  159,  105],
        [ 168,   86,    3,   78,  147]], dtype=torch.int32)

In [49]:
device = torch.device("cuda:0")
model.cuda()
for attr in batch:
    batch[attr] = batch[attr].to(device)
loss = model.loss(batch)

2019-06-04 16:43:43,261 - INFO - few_shot_statistic_pooling - loss: 456.25457763671875, acc: 0.05999999865889549 
INFO:protonets.models.few_shot_statistic_pooling:loss: 456.25457763671875, acc: 0.05999999865889549


In [45]:
num_para = 0
for parameter in model.parameters():
    num = 1
    for s in parameter.shape:
        num *= s
    num_para += num
print(num_para)

6027464


In [11]:
m = nn.Conv1d(16, 33, 5, padding=2)
input = torch.randn(20, 16, 50)
output = m(input)

In [12]:
torch.arange(10)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [ ]:
loss

In [19]:
x = torch.rand(10, 200, 60)
lengths = torch.rand(10)*200
a = torch.arange(x.size(1))[None, :] < lengths[:, None].float()

In [25]:
a[:, :, None].expand(*a.shape, 5)

tensor([[[ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         ...,
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         ...,
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         ...,
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        ...,

        [[ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         ...,
         [ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1]],

        [[ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         [ 1,  1,  1,  1,  1],
         ...,
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         